SELECT
  COD_CLIENTE_OLTP
, NOM_CLIENTE
, EML_CLIENTE
, NOM_CIDADE_CLIENTE
, LOGRADOURO + ' -Num: '+ CONVERT(varchar(5), NUMERO) +' Complemento:'+ COMPLEMENTO  +' CEP: '+ CEP END_CLIENTE
FROM TB_STG_CLIENTE