

---Script auxliar TB_DIM_CATEGORIA_PRODUTO

		USE DW;

			ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD VERSAO INT
			;
			ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD DATA_INICIO_VIGENCIA DATETIME
			;
			ALTER TABLE DBO.TB_DIM_CATEGORIA_PRODUTO ADD DATA_FIM_VIGENCIA DATETIME

            SELECT * FROM DBO.TB_DIM_CATEGORIA_PRODUTO
			ORDER BY 2;

			---inserção SRK=0
			INSERT INTO DBO.TB_DIM_CATEGORIA_PRODUTO VALUES (0,0,'SCD2',NULL, NULL, NULL);

			

		---TESTE GERAÇÃO VERSÃO - SCD2
			USE STG;

			SELECT * FROM [dbo].[TB_STG_CATEGORIA_PRODUTO] ;

			UPDATE [dbo].[TB_STG_CATEGORIA_PRODUTO] 
			SET [DES_CATEGORIA_PRODUTO] = 'TENIS'
			WHERE [COD_CATEGORIA_PRODUTO_OLTP]=140