/****** Script do comando SelectTopNRows de SSMS  ******/
USE DW;
SELECT * FROM [dbo].[TB_DIM_PRODUTO]
WHERE COD_PRODUTO_NK = 11




USE STG;
SELECT * FROM [dbo].[TB_STG_PRODUTO]
WHERE COD_PRODUTO_OLTP = 11


USE DW;
SELECT * FROM [dbo].[TB_DIM_CATEGORIA_PRODUTO]
WHERE COD_CATEGORIA_PRODUTO_NK = 80