USE STG

SELECT 
YEAR(P.DATA_PEDIDO) * 100 + MONTH(P.DATA_PEDIDO) AS NUM_MES_PEDIDO,
CLI.COD_ESTADO_OLTP,
CLI.COD_CLIENTE_OLTP,
CLI.COD_TIPO_CLIENTE_OLTP,
I.COD_PRODUTO_OLTP,
SUM(I.VLR_UNITARIO_ITEM * I.QTD_ITEM) VLR_PEDIDO,
SUM (I.QTD_ITEM) QTD_ITEM_PEDIDO,
(YEAR (GETDATE())*100 + MONTH(GETDATE())) *100 +  DAY(GETDATE()) AS DATA_CARGA

FROM   TB_STG_ITEM_PEDIDO AS I  
               INNER JOIN  TB_STG_PEDIDO   AS  P   ON (P.COD_PEDIDO_OLTP=I.COD_PEDIDO_OLTP)
               INNER JOIN TB_STG_CLIENTE AS CLI ON (P.COD_CLIENTE_OLTP=CLI.COD_CLIENTE_OLTP)

GROUP BY
YEAR(P.DATA_PEDIDO) * 100 + MONTH(P.DATA_PEDIDO) ,
CLI.COD_ESTADO_OLTP,
CLI.COD_CLIENTE_OLTP,
CLI.COD_TIPO_CLIENTE_OLTP,
I.COD_PRODUTO_OLTP

